[package]
name = "moomoot"
version = "0.1.0"
authors = ["Florent D'halluin <flal@melix.net>"]

[dependencies]
jack = "0.5.0"
libc = "0.2.0"
rand = "0.3"
# rosc = "~0.1"
# matches="0.1"
uuid = {version = "0.4", features = ["v4"]}
